

export interface Stats {
    uploadedBytes: number;
    downloadedBytes: number;
    filesAdded: number;
    sessionCount: number;
    secondsActive: number;
}

export interface SessionStats {
    activeTorrentCount?: number;
    downloadSpeed?: number;
    pausedTorrentCount?: number;
    torrentCount?: number;
    uploadSpeed?: number;
    ["cumulative-stats"]?: Stats;
    ["current-stats"]?: Stats;
}

export interface Torrent {
    activityDate?: number;
    addedDate?: number;
    bandwidthPriority?: number;
    comment?: string;
    corruptEver?: number;
    creator?: string;
    dateCreated?: number;
    desiredAvailable?: number;
    doneDate?: number;
    downloadDir?: string;
    downloadedEver?: number;
    downloadLimit?: number;
    downloadLimited?: boolean;
    error?: number;
    errorString?: string;
    eta?: number;
    etaIdle?: number;
    files?: any[];
    fileStats?: any[];
    hashString?: string;
    haveUnchecked?: number;
    haveValid?: number;
    honorsSessionLimits?: boolean;
    id?: number;
    isFinished?: boolean;
    isPrivate?: boolean;
    isStalled?: boolean;
    leftUntilDone?: number;
    magnetLink?: string;
    manualAnnounceTime?: number;
    maxConnectedPeers?: number;
    metadataPercentComplete?: number;
    name?: string;
    ["peer-limit"]?: number;
    peers?: any[];
    peersConnected?: number;
    peersFrom?: any;
    peersGettingFromUs?: number;
    peersSendingToUs?: number;
    percentDone?: number;
    pieces?: string;
    pieceCount?: number;
    pieceSize?: number;
    priorities?: any[];
    queuePosition?: number;
    rateDownload?: number; // B/s
    rateUpload?: number; // B/s
    recheckProgress?: number;
    secondsDownloading?: number;
    secondsSeeding?: number;
    seedIdleLimit?: number;
    seedIdleMode?: number;
    seedRatioLimit?: number;
    seedRatioMode?: number;
    sizeWhenDone?: number;
    startDate?: number;
    status?: number;
    trackers?: any[];
    trackerStats?: any[];
    totalSize?: number;
    torrentFile?: string;
    uploadedEver?: number;
    uploadLimit?: number;
    uploadLimited?: boolean;
    uploadRatio?: number;
    wanted?: any[];
    webseeds?: any[];
    webseedsSendingToUs?: number;
}

export const all_torrents_fields = [, "activityDate"
    , "addedDate"
    , "bandwidthPriority"
    , "comment"
    , "corruptEver"
    , "creator"
    , "dateCreated"
    , "desiredAvailable"
    , "doneDate"
    , "downloadDir"
    , "downloadedEver"
    , "downloadLimit"
    , "downloadLimited"
    , "error"
    , "errorString"
    , "eta"
    , "etaIdle"
    , "files"
    , "fileStats"
    , "hashString"
    , "haveUnchecked"
    , "haveValid"
    , "honorsSessionLimits"
    , "id"
    , "isFinished"
    , "isPrivate"
    , "isStalled"
    , "leftUntilDone"
    , "magnetLink"
    , "manualAnnounceTime"
    , "maxConnectedPeers"
    , "metadataPercentComplete"
    , "name"
    , "peer-limit"
    , "peers"
    , "peersConnected"
    , "peersFrom"
    , "peersGettingFromUs"
    , "peersSendingToUs"
    , "percentDone"
    , "pieces"
    , "pieceCount"
    , "pieceSize"
    , "priorities"
    , "queuePosition"
    , "rateDownload"
    , "rateUpload"
    , "recheckProgress"
    , "secondsDownloading"
    , "secondsSeeding"
    , "seedIdleLimit"
    , "seedIdleMode"
    , "seedRatioLimit"
    , "seedRatioMode"
    , "sizeWhenDone"
    , "startDate"
    , "status"
    , "trackers"
    , "trackerStats"
    , "totalSize"
    , "torrentFile"
    , "uploadedEver"
    , "uploadLimit"
    , "uploadLimited"
    , "uploadRatio"
    , "wanted"
    , "webseeds"
    , "webseedsSendingToUs"]